"""create_multi_tenant_and_demands

Revision ID: 2a4a8c4fb132
Revises: 3a77f541b624
Create Date: 2026-07-06 23:52:01.867327

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '2a4a8c4fb132'
down_revision: Union[str, Sequence[str], None] = '3a77f541b624'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('tenants',
    sa.Column('id', sa.BigInteger(), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('tenant_type', sa.String(length=50), nullable=False),
    sa.Column('slug', sa.String(length=255), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_tenants_id'), 'tenants', ['id'], unique=False)
    op.create_index(op.f('ix_tenants_slug'), 'tenants', ['slug'], unique=True)
    op.create_table('ngo_demands',
    sa.Column('id', sa.BigInteger(), nullable=False),
    sa.Column('tenant_id', sa.BigInteger(), nullable=False),
    sa.Column('ngo_id', sa.BigInteger(), nullable=False),
    sa.Column('title', sa.String(length=255), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('priority', sa.String(length=50), nullable=False),
    sa.Column('status', sa.String(length=50), nullable=False),
    sa.Column('city', sa.String(length=100), nullable=False),
    sa.Column('needed_by_date', sa.Date(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['ngo_id'], ['users.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenants.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_ngo_demands_id'), 'ngo_demands', ['id'], unique=False)
    op.create_index(op.f('ix_ngo_demands_ngo_id'), 'ngo_demands', ['ngo_id'], unique=False)
    op.create_index(op.f('ix_ngo_demands_tenant_id'), 'ngo_demands', ['tenant_id'], unique=False)
    op.create_table('ngo_demand_items',
    sa.Column('id', sa.BigInteger(), nullable=False),
    sa.Column('demand_id', sa.BigInteger(), nullable=False),
    sa.Column('item_name', sa.String(length=255), nullable=False),
    sa.Column('category', sa.String(length=100), nullable=False),
    sa.Column('quantity_needed', sa.Integer(), nullable=False),
    sa.Column('quantity_fulfilled', sa.Integer(), nullable=False),
    sa.Column('minimum_condition', sa.String(length=50), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['demand_id'], ['ngo_demands.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_ngo_demand_items_demand_id'), 'ngo_demand_items', ['demand_id'], unique=False)
    op.create_index(op.f('ix_ngo_demand_items_id'), 'ngo_demand_items', ['id'], unique=False)
    op.create_table('packaging_records',
    sa.Column('id', sa.BigInteger(), nullable=False),
    sa.Column('donation_id', sa.BigInteger(), nullable=False),
    sa.Column('packaging_status', sa.String(length=50), nullable=False),
    sa.Column('package_count', sa.Integer(), nullable=False),
    sa.Column('packaging_notes', sa.Text(), nullable=True),
    sa.Column('completed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['donation_id'], ['donations.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_packaging_records_donation_id'), 'packaging_records', ['donation_id'], unique=True)
    op.create_index(op.f('ix_packaging_records_id'), 'packaging_records', ['id'], unique=False)
    op.add_column('ngo_profiles', sa.Column('tenant_id', sa.BigInteger(), nullable=True))
    op.create_foreign_key('fk_ngo_profiles_tenant_id_tenants', 'ngo_profiles', 'tenants', ['tenant_id'], ['id'], ondelete='CASCADE')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('fk_ngo_profiles_tenant_id_tenants', 'ngo_profiles', type_='foreignkey')
    op.drop_column('ngo_profiles', 'tenant_id')
    op.drop_index(op.f('ix_packaging_records_id'), table_name='packaging_records')
    op.drop_index(op.f('ix_packaging_records_donation_id'), table_name='packaging_records')
    op.drop_table('packaging_records')
    op.drop_index(op.f('ix_ngo_demand_items_id'), table_name='ngo_demand_items')
    op.drop_index(op.f('ix_ngo_demand_items_demand_id'), table_name='ngo_demand_items')
    op.drop_table('ngo_demand_items')
    op.drop_index(op.f('ix_ngo_demands_tenant_id'), table_name='ngo_demands')
    op.drop_index(op.f('ix_ngo_demands_ngo_id'), table_name='ngo_demands')
    op.drop_index(op.f('ix_ngo_demands_id'), table_name='ngo_demands')
    op.drop_table('ngo_demands')
    op.drop_index(op.f('ix_tenants_slug'), table_name='tenants')
    op.drop_index(op.f('ix_tenants_id'), table_name='tenants')
    op.drop_table('tenants')
    # ### end Alembic commands ###
