"""align_legacy_indexes

Revision ID: 2e904720e94a
Revises: 2a4a8c4fb132
Create Date: 2026-07-07 00:08:39.344217

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '2e904720e94a'
down_revision: Union[str, Sequence[str], None] = '2a4a8c4fb132'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index(op.f('ix_donor_profiles_id'), 'donor_profiles', ['id'], unique=False)
    op.create_index(op.f('ix_ngo_focus_areas_id'), 'ngo_focus_areas', ['id'], unique=False)
    op.drop_index(op.f('idx_ngo_city'), table_name='ngo_profiles')
    op.create_index(op.f('ix_ngo_profiles_city'), 'ngo_profiles', ['city'], unique=False)
    op.create_index(op.f('ix_ngo_profiles_id'), 'ngo_profiles', ['id'], unique=False)
    op.drop_index(op.f('idx_users_email'), table_name='users')
    op.drop_index(op.f('idx_users_role'), table_name='users')
    op.drop_constraint(op.f('users_email_key'), 'users', type_='unique')
    op.create_index(op.f('ix_users_email'), 'users', ['email'], unique=True)
    op.create_index(op.f('ix_users_id'), 'users', ['id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_users_id'), table_name='users')
    op.drop_index(op.f('ix_users_email'), table_name='users')
    op.create_unique_constraint(op.f('users_email_key'), 'users', ['email'], postgresql_nulls_not_distinct=False)
    op.create_index(op.f('idx_users_role'), 'users', ['role'], unique=False)
    op.create_index(op.f('idx_users_email'), 'users', ['email'], unique=False)
    op.drop_index(op.f('ix_ngo_profiles_id'), table_name='ngo_profiles')
    op.drop_index(op.f('ix_ngo_profiles_city'), table_name='ngo_profiles')
    op.create_index(op.f('idx_ngo_city'), 'ngo_profiles', ['city'], unique=False)
    op.drop_index(op.f('ix_ngo_focus_areas_id'), table_name='ngo_focus_areas')
    op.drop_index(op.f('ix_donor_profiles_id'), table_name='donor_profiles')
    # ### end Alembic commands ###
