"""create_donation_workflow_tables

Revision ID: 3a77f541b624
Revises: 
Create Date: 2026-07-06 23:13:23.522937

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '3a77f541b624'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('donations',
    sa.Column('id', sa.BigInteger(), nullable=False),
    sa.Column('donor_id', sa.BigInteger(), nullable=False),
    sa.Column('ngo_id', sa.BigInteger(), nullable=True),
    sa.Column('status', sa.String(length=50), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['donor_id'], ['users.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['ngo_id'], ['users.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_donations_donor_id'), 'donations', ['donor_id'], unique=False)
    op.create_index(op.f('ix_donations_id'), 'donations', ['id'], unique=False)
    op.create_index(op.f('ix_donations_ngo_id'), 'donations', ['ngo_id'], unique=False)
    op.create_index(op.f('ix_donations_status'), 'donations', ['status'], unique=False)
    op.create_table('notifications',
    sa.Column('id', sa.BigInteger(), nullable=False),
    sa.Column('user_id', sa.BigInteger(), nullable=False),
    sa.Column('title', sa.String(length=255), nullable=False),
    sa.Column('message', sa.Text(), nullable=False),
    sa.Column('type', sa.String(length=50), nullable=False),
    sa.Column('related_request_id', sa.BigInteger(), nullable=True),
    sa.Column('is_read', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_notifications_id'), 'notifications', ['id'], unique=False)
    op.create_index(op.f('ix_notifications_user_id'), 'notifications', ['user_id'], unique=False)
    op.create_table('donation_items',
    sa.Column('id', sa.BigInteger(), nullable=False),
    sa.Column('donation_id', sa.BigInteger(), nullable=False),
    sa.Column('item_name', sa.String(length=255), nullable=False),
    sa.Column('category', sa.String(length=100), nullable=False),
    sa.Column('quantity', sa.Integer(), nullable=False),
    sa.Column('condition', sa.String(length=50), nullable=False),
    sa.Column('confidence_score', sa.Float(), nullable=True),
    sa.Column('source', sa.String(length=50), nullable=False),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.CheckConstraint('confidence_score >= 0.0 AND confidence_score <= 1.0', name='donation_items_confidence_check'),
    sa.CheckConstraint('quantity > 0', name='donation_items_quantity_check'),
    sa.ForeignKeyConstraint(['donation_id'], ['donations.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_donation_items_donation_id'), 'donation_items', ['donation_id'], unique=False)
    op.create_index(op.f('ix_donation_items_id'), 'donation_items', ['id'], unique=False)
    op.create_table('donation_requests',
    sa.Column('id', sa.BigInteger(), nullable=False),
    sa.Column('donation_id', sa.BigInteger(), nullable=False),
    sa.Column('donor_id', sa.BigInteger(), nullable=False),
    sa.Column('ngo_id', sa.BigInteger(), nullable=False),
    sa.Column('status', sa.String(length=50), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['donation_id'], ['donations.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['donor_id'], ['users.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['ngo_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_donation_requests_donation_id'), 'donation_requests', ['donation_id'], unique=False)
    op.create_index(op.f('ix_donation_requests_id'), 'donation_requests', ['id'], unique=False)
    op.create_index(op.f('ix_donation_requests_ngo_id'), 'donation_requests', ['ngo_id'], unique=False)
    op.create_index(op.f('ix_donation_requests_status'), 'donation_requests', ['status'], unique=False)
    op.create_table('donation_status_history',
    sa.Column('id', sa.BigInteger(), nullable=False),
    sa.Column('donation_id', sa.BigInteger(), nullable=False),
    sa.Column('old_status', sa.String(length=50), nullable=False),
    sa.Column('new_status', sa.String(length=50), nullable=False),
    sa.Column('changed_by_user_id', sa.BigInteger(), nullable=False),
    sa.Column('note', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['changed_by_user_id'], ['users.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['donation_id'], ['donations.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_donation_status_history_donation_id'), 'donation_status_history', ['donation_id'], unique=False)
    op.create_index(op.f('ix_donation_status_history_id'), 'donation_status_history', ['id'], unique=False)
    op.create_table('pickup_schedules',
    sa.Column('id', sa.BigInteger(), nullable=False),
    sa.Column('donation_id', sa.BigInteger(), nullable=False),
    sa.Column('pickup_date', sa.Date(), nullable=False),
    sa.Column('time_slot', sa.String(length=100), nullable=False),
    sa.Column('pickup_address', sa.Text(), nullable=False),
    sa.Column('contact_phone', sa.String(length=50), nullable=False),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['donation_id'], ['donations.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_pickup_schedules_donation_id'), 'pickup_schedules', ['donation_id'], unique=True)
    op.create_index(op.f('ix_pickup_schedules_id'), 'pickup_schedules', ['id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_pickup_schedules_id'), table_name='pickup_schedules')
    op.drop_index(op.f('ix_pickup_schedules_donation_id'), table_name='pickup_schedules')
    op.drop_table('pickup_schedules')
    op.drop_index(op.f('ix_donation_status_history_id'), table_name='donation_status_history')
    op.drop_index(op.f('ix_donation_status_history_donation_id'), table_name='donation_status_history')
    op.drop_table('donation_status_history')
    op.drop_index(op.f('ix_donation_requests_status'), table_name='donation_requests')
    op.drop_index(op.f('ix_donation_requests_ngo_id'), table_name='donation_requests')
    op.drop_index(op.f('ix_donation_requests_id'), table_name='donation_requests')
    op.drop_index(op.f('ix_donation_requests_donation_id'), table_name='donation_requests')
    op.drop_table('donation_requests')
    op.drop_index(op.f('ix_donation_items_id'), table_name='donation_items')
    op.drop_index(op.f('ix_donation_items_donation_id'), table_name='donation_items')
    op.drop_table('donation_items')
    op.drop_index(op.f('ix_notifications_user_id'), table_name='notifications')
    op.drop_index(op.f('ix_notifications_id'), table_name='notifications')
    op.drop_table('notifications')
    op.drop_index(op.f('ix_donations_status'), table_name='donations')
    op.drop_index(op.f('ix_donations_ngo_id'), table_name='donations')
    op.drop_index(op.f('ix_donations_id'), table_name='donations')
    op.drop_index(op.f('ix_donations_donor_id'), table_name='donations')
    op.drop_table('donations')
    # ### end Alembic commands ###
