"""add_volunteer_email

Revision ID: 5f47bc0ab3a0
Revises: f88f62610583
Create Date: 2026-07-20 22:06:59.286468

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '5f47bc0ab3a0'
down_revision: Union[str, Sequence[str], None] = 'f88f62610583'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('pickup_schedules', sa.Column('volunteer_email', sa.String(length=255), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('pickup_schedules', 'volunteer_email')
    # ### end Alembic commands ###
