"""add_donation_matches_and_embeddings

Revision ID: f7d968b5674c
Revises: 2e904720e94a
Create Date: 2026-07-07 17:29:01.885976

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'f7d968b5674c'
down_revision: Union[str, Sequence[str], None] = '2e904720e94a'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('donation_matches',
    sa.Column('id', sa.BigInteger(), nullable=False),
    sa.Column('donation_id', sa.BigInteger(), nullable=False),
    sa.Column('ngo_id', sa.BigInteger(), nullable=False),
    sa.Column('tenant_id', sa.BigInteger(), nullable=False),
    sa.Column('demand_id', sa.BigInteger(), nullable=False),
    sa.Column('final_score', sa.Float(), nullable=False),
    sa.Column('item_match_score', sa.Float(), nullable=False),
    sa.Column('quantity_fit_score', sa.Float(), nullable=False),
    sa.Column('geographic_score', sa.Float(), nullable=False),
    sa.Column('priority_score', sa.Float(), nullable=False),
    sa.Column('matched_items_count', sa.Integer(), nullable=False),
    sa.Column('match_explanation', sa.Text(), nullable=False),
    sa.Column('status', sa.String(length=50), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['demand_id'], ['ngo_demands.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['donation_id'], ['donations.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['ngo_id'], ['ngo_profiles.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenants.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('donation_id', 'ngo_id', 'demand_id', name='uq_donation_match_key')
    )
    op.create_index(op.f('ix_donation_matches_demand_id'), 'donation_matches', ['demand_id'], unique=False)
    op.create_index(op.f('ix_donation_matches_donation_id'), 'donation_matches', ['donation_id'], unique=False)
    op.create_index(op.f('ix_donation_matches_id'), 'donation_matches', ['id'], unique=False)
    op.create_index(op.f('ix_donation_matches_ngo_id'), 'donation_matches', ['ngo_id'], unique=False)
    op.create_index(op.f('ix_donation_matches_status'), 'donation_matches', ['status'], unique=False)
    op.create_index(op.f('ix_donation_matches_tenant_id'), 'donation_matches', ['tenant_id'], unique=False)
    op.add_column('donation_items', sa.Column('embedding', sa.ARRAY(sa.Float()), nullable=True))
    op.add_column('ngo_demand_items', sa.Column('embedding', sa.ARRAY(sa.Float()), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('ngo_demand_items', 'embedding')
    op.drop_column('donation_items', 'embedding')
    op.drop_index(op.f('ix_donation_matches_tenant_id'), table_name='donation_matches')
    op.drop_index(op.f('ix_donation_matches_status'), table_name='donation_matches')
    op.drop_index(op.f('ix_donation_matches_ngo_id'), table_name='donation_matches')
    op.drop_index(op.f('ix_donation_matches_id'), table_name='donation_matches')
    op.drop_index(op.f('ix_donation_matches_donation_id'), table_name='donation_matches')
    op.drop_index(op.f('ix_donation_matches_demand_id'), table_name='donation_matches')
    op.drop_table('donation_matches')
    # ### end Alembic commands ###
