"""add_volunteer_fields

Revision ID: f88f62610583
Revises: f9c0e6adf232
Create Date: 2026-07-20 21:27:29.385977

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'f88f62610583'
down_revision: Union[str, Sequence[str], None] = 'f9c0e6adf232'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('pickup_schedules', sa.Column('volunteer_name', sa.String(length=255), nullable=True))
    op.add_column('pickup_schedules', sa.Column('volunteer_phone', sa.String(length=50), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('pickup_schedules', 'volunteer_phone')
    op.drop_column('pickup_schedules', 'volunteer_name')
    # ### end Alembic commands ###
