"""add_workflow_columns

Revision ID: f9c0e6adf232
Revises: a34e241d95ea
Create Date: 2026-07-20 18:59:37.390631

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'f9c0e6adf232'
down_revision: Union[str, Sequence[str], None] = 'a34e241d95ea'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('packaging_records', sa.Column('completed_items', sa.Text(), nullable=True))
    op.add_column('pickup_schedules', sa.Column('reminder_status', sa.String(length=50), server_default='PENDING', nullable=False))
    op.add_column('users', sa.Column('email_notifications_enabled', sa.Boolean(), server_default='true', nullable=False))
    op.add_column('users', sa.Column('inapp_notifications_enabled', sa.Boolean(), server_default='true', nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'inapp_notifications_enabled')
    op.drop_column('users', 'email_notifications_enabled')
    op.drop_column('pickup_schedules', 'reminder_status')
    op.drop_column('packaging_records', 'completed_items')
    # ### end Alembic commands ###
