/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as RegisterRouteImport } from './routes/register'
import { Route as NgoRouteImport } from './routes/ngo'
import { Route as LoginRouteImport } from './routes/login'
import { Route as HowItWorksRouteImport } from './routes/how-it-works'
import { Route as FindNgosRouteImport } from './routes/find-ngos'
import { Route as FaqRouteImport } from './routes/faq'
import { Route as DonorRouteImport } from './routes/donor'
import { Route as ContactRouteImport } from './routes/contact'
import { Route as AdminRouteImport } from './routes/admin'
import { Route as AboutRouteImport } from './routes/about'
import { Route as IndexRouteImport } from './routes/index'
import { Route as RegisterIndexRouteImport } from './routes/register.index'
import { Route as RegisterNgoRouteImport } from './routes/register.ngo'
import { Route as RegisterDonorRouteImport } from './routes/register.donor'
import { Route as NgoProfileRouteImport } from './routes/ngo.profile'
import { Route as NgoNotificationsRouteImport } from './routes/ngo.notifications'
import { Route as NgoIncomingRouteImport } from './routes/ngo.incoming'
import { Route as NgoDemandsRouteImport } from './routes/ngo.demands'
import { Route as NgoDashboardRouteImport } from './routes/ngo.dashboard'
import { Route as DonorScheduleRouteImport } from './routes/donor.schedule'
import { Route as DonorReviewRouteImport } from './routes/donor.review'
import { Route as DonorProfileRouteImport } from './routes/donor.profile'
import { Route as DonorPackagingRouteImport } from './routes/donor.packaging'
import { Route as DonorNotificationsRouteImport } from './routes/donor.notifications'
import { Route as DonorMatchesRouteImport } from './routes/donor.matches'
import { Route as DonorImpactRouteImport } from './routes/donor.impact'
import { Route as DonorDonationsRouteImport } from './routes/donor.donations'
import { Route as DonorDonateRouteImport } from './routes/donor.donate'
import { Route as DonorDetectionsRouteImport } from './routes/donor.detections'
import { Route as DonorDashboardRouteImport } from './routes/donor.dashboard'
import { Route as DonorCameraRouteImport } from './routes/donor.camera'
import { Route as AdminSystemHealthRouteImport } from './routes/admin.system-health'
import { Route as AdminNgosRouteImport } from './routes/admin.ngos'
import { Route as AdminDashboardRouteImport } from './routes/admin.dashboard'
import { Route as AdminAnalyticsRouteImport } from './routes/admin.analytics'
import { Route as NgoDemandsIndexRouteImport } from './routes/ngo.demands.index'
import { Route as NgoDemandsNewRouteImport } from './routes/ngo.demands.new'
import { Route as DonorTrackIdRouteImport } from './routes/donor.track.$id'
import { Route as DonorMatchesIdRouteImport } from './routes/donor.matches.$id'

const RegisterRoute = RegisterRouteImport.update({
  id: '/register',
  path: '/register',
  getParentRoute: () => rootRouteImport,
} as any)
const NgoRoute = NgoRouteImport.update({
  id: '/ngo',
  path: '/ngo',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const HowItWorksRoute = HowItWorksRouteImport.update({
  id: '/how-it-works',
  path: '/how-it-works',
  getParentRoute: () => rootRouteImport,
} as any)
const FindNgosRoute = FindNgosRouteImport.update({
  id: '/find-ngos',
  path: '/find-ngos',
  getParentRoute: () => rootRouteImport,
} as any)
const FaqRoute = FaqRouteImport.update({
  id: '/faq',
  path: '/faq',
  getParentRoute: () => rootRouteImport,
} as any)
const DonorRoute = DonorRouteImport.update({
  id: '/donor',
  path: '/donor',
  getParentRoute: () => rootRouteImport,
} as any)
const ContactRoute = ContactRouteImport.update({
  id: '/contact',
  path: '/contact',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminRoute = AdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => rootRouteImport,
} as any)
const AboutRoute = AboutRouteImport.update({
  id: '/about',
  path: '/about',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const RegisterIndexRoute = RegisterIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => RegisterRoute,
} as any)
const RegisterNgoRoute = RegisterNgoRouteImport.update({
  id: '/ngo',
  path: '/ngo',
  getParentRoute: () => RegisterRoute,
} as any)
const RegisterDonorRoute = RegisterDonorRouteImport.update({
  id: '/donor',
  path: '/donor',
  getParentRoute: () => RegisterRoute,
} as any)
const NgoProfileRoute = NgoProfileRouteImport.update({
  id: '/profile',
  path: '/profile',
  getParentRoute: () => NgoRoute,
} as any)
const NgoNotificationsRoute = NgoNotificationsRouteImport.update({
  id: '/notifications',
  path: '/notifications',
  getParentRoute: () => NgoRoute,
} as any)
const NgoIncomingRoute = NgoIncomingRouteImport.update({
  id: '/incoming',
  path: '/incoming',
  getParentRoute: () => NgoRoute,
} as any)
const NgoDemandsRoute = NgoDemandsRouteImport.update({
  id: '/demands',
  path: '/demands',
  getParentRoute: () => NgoRoute,
} as any)
const NgoDashboardRoute = NgoDashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => NgoRoute,
} as any)
const DonorScheduleRoute = DonorScheduleRouteImport.update({
  id: '/schedule',
  path: '/schedule',
  getParentRoute: () => DonorRoute,
} as any)
const DonorReviewRoute = DonorReviewRouteImport.update({
  id: '/review',
  path: '/review',
  getParentRoute: () => DonorRoute,
} as any)
const DonorProfileRoute = DonorProfileRouteImport.update({
  id: '/profile',
  path: '/profile',
  getParentRoute: () => DonorRoute,
} as any)
const DonorPackagingRoute = DonorPackagingRouteImport.update({
  id: '/packaging',
  path: '/packaging',
  getParentRoute: () => DonorRoute,
} as any)
const DonorNotificationsRoute = DonorNotificationsRouteImport.update({
  id: '/notifications',
  path: '/notifications',
  getParentRoute: () => DonorRoute,
} as any)
const DonorMatchesRoute = DonorMatchesRouteImport.update({
  id: '/matches',
  path: '/matches',
  getParentRoute: () => DonorRoute,
} as any)
const DonorImpactRoute = DonorImpactRouteImport.update({
  id: '/impact',
  path: '/impact',
  getParentRoute: () => DonorRoute,
} as any)
const DonorDonationsRoute = DonorDonationsRouteImport.update({
  id: '/donations',
  path: '/donations',
  getParentRoute: () => DonorRoute,
} as any)
const DonorDonateRoute = DonorDonateRouteImport.update({
  id: '/donate',
  path: '/donate',
  getParentRoute: () => DonorRoute,
} as any)
const DonorDetectionsRoute = DonorDetectionsRouteImport.update({
  id: '/detections',
  path: '/detections',
  getParentRoute: () => DonorRoute,
} as any)
const DonorDashboardRoute = DonorDashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => DonorRoute,
} as any)
const DonorCameraRoute = DonorCameraRouteImport.update({
  id: '/camera',
  path: '/camera',
  getParentRoute: () => DonorRoute,
} as any)
const AdminSystemHealthRoute = AdminSystemHealthRouteImport.update({
  id: '/system-health',
  path: '/system-health',
  getParentRoute: () => AdminRoute,
} as any)
const AdminNgosRoute = AdminNgosRouteImport.update({
  id: '/ngos',
  path: '/ngos',
  getParentRoute: () => AdminRoute,
} as any)
const AdminDashboardRoute = AdminDashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => AdminRoute,
} as any)
const AdminAnalyticsRoute = AdminAnalyticsRouteImport.update({
  id: '/analytics',
  path: '/analytics',
  getParentRoute: () => AdminRoute,
} as any)
const NgoDemandsIndexRoute = NgoDemandsIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => NgoDemandsRoute,
} as any)
const NgoDemandsNewRoute = NgoDemandsNewRouteImport.update({
  id: '/new',
  path: '/new',
  getParentRoute: () => NgoDemandsRoute,
} as any)
const DonorTrackIdRoute = DonorTrackIdRouteImport.update({
  id: '/track/$id',
  path: '/track/$id',
  getParentRoute: () => DonorRoute,
} as any)
const DonorMatchesIdRoute = DonorMatchesIdRouteImport.update({
  id: '/$id',
  path: '/$id',
  getParentRoute: () => DonorMatchesRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/admin': typeof AdminRouteWithChildren
  '/contact': typeof ContactRoute
  '/donor': typeof DonorRouteWithChildren
  '/faq': typeof FaqRoute
  '/find-ngos': typeof FindNgosRoute
  '/how-it-works': typeof HowItWorksRoute
  '/login': typeof LoginRoute
  '/ngo': typeof NgoRouteWithChildren
  '/register': typeof RegisterRouteWithChildren
  '/admin/analytics': typeof AdminAnalyticsRoute
  '/admin/dashboard': typeof AdminDashboardRoute
  '/admin/ngos': typeof AdminNgosRoute
  '/admin/system-health': typeof AdminSystemHealthRoute
  '/donor/camera': typeof DonorCameraRoute
  '/donor/dashboard': typeof DonorDashboardRoute
  '/donor/detections': typeof DonorDetectionsRoute
  '/donor/donate': typeof DonorDonateRoute
  '/donor/donations': typeof DonorDonationsRoute
  '/donor/impact': typeof DonorImpactRoute
  '/donor/matches': typeof DonorMatchesRouteWithChildren
  '/donor/notifications': typeof DonorNotificationsRoute
  '/donor/packaging': typeof DonorPackagingRoute
  '/donor/profile': typeof DonorProfileRoute
  '/donor/review': typeof DonorReviewRoute
  '/donor/schedule': typeof DonorScheduleRoute
  '/ngo/dashboard': typeof NgoDashboardRoute
  '/ngo/demands': typeof NgoDemandsRouteWithChildren
  '/ngo/incoming': typeof NgoIncomingRoute
  '/ngo/notifications': typeof NgoNotificationsRoute
  '/ngo/profile': typeof NgoProfileRoute
  '/register/donor': typeof RegisterDonorRoute
  '/register/ngo': typeof RegisterNgoRoute
  '/register/': typeof RegisterIndexRoute
  '/donor/matches/$id': typeof DonorMatchesIdRoute
  '/donor/track/$id': typeof DonorTrackIdRoute
  '/ngo/demands/new': typeof NgoDemandsNewRoute
  '/ngo/demands/': typeof NgoDemandsIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/admin': typeof AdminRouteWithChildren
  '/contact': typeof ContactRoute
  '/donor': typeof DonorRouteWithChildren
  '/faq': typeof FaqRoute
  '/find-ngos': typeof FindNgosRoute
  '/how-it-works': typeof HowItWorksRoute
  '/login': typeof LoginRoute
  '/ngo': typeof NgoRouteWithChildren
  '/admin/analytics': typeof AdminAnalyticsRoute
  '/admin/dashboard': typeof AdminDashboardRoute
  '/admin/ngos': typeof AdminNgosRoute
  '/admin/system-health': typeof AdminSystemHealthRoute
  '/donor/camera': typeof DonorCameraRoute
  '/donor/dashboard': typeof DonorDashboardRoute
  '/donor/detections': typeof DonorDetectionsRoute
  '/donor/donate': typeof DonorDonateRoute
  '/donor/donations': typeof DonorDonationsRoute
  '/donor/impact': typeof DonorImpactRoute
  '/donor/matches': typeof DonorMatchesRouteWithChildren
  '/donor/notifications': typeof DonorNotificationsRoute
  '/donor/packaging': typeof DonorPackagingRoute
  '/donor/profile': typeof DonorProfileRoute
  '/donor/review': typeof DonorReviewRoute
  '/donor/schedule': typeof DonorScheduleRoute
  '/ngo/dashboard': typeof NgoDashboardRoute
  '/ngo/incoming': typeof NgoIncomingRoute
  '/ngo/notifications': typeof NgoNotificationsRoute
  '/ngo/profile': typeof NgoProfileRoute
  '/register/donor': typeof RegisterDonorRoute
  '/register/ngo': typeof RegisterNgoRoute
  '/register': typeof RegisterIndexRoute
  '/donor/matches/$id': typeof DonorMatchesIdRoute
  '/donor/track/$id': typeof DonorTrackIdRoute
  '/ngo/demands/new': typeof NgoDemandsNewRoute
  '/ngo/demands': typeof NgoDemandsIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/admin': typeof AdminRouteWithChildren
  '/contact': typeof ContactRoute
  '/donor': typeof DonorRouteWithChildren
  '/faq': typeof FaqRoute
  '/find-ngos': typeof FindNgosRoute
  '/how-it-works': typeof HowItWorksRoute
  '/login': typeof LoginRoute
  '/ngo': typeof NgoRouteWithChildren
  '/register': typeof RegisterRouteWithChildren
  '/admin/analytics': typeof AdminAnalyticsRoute
  '/admin/dashboard': typeof AdminDashboardRoute
  '/admin/ngos': typeof AdminNgosRoute
  '/admin/system-health': typeof AdminSystemHealthRoute
  '/donor/camera': typeof DonorCameraRoute
  '/donor/dashboard': typeof DonorDashboardRoute
  '/donor/detections': typeof DonorDetectionsRoute
  '/donor/donate': typeof DonorDonateRoute
  '/donor/donations': typeof DonorDonationsRoute
  '/donor/impact': typeof DonorImpactRoute
  '/donor/matches': typeof DonorMatchesRouteWithChildren
  '/donor/notifications': typeof DonorNotificationsRoute
  '/donor/packaging': typeof DonorPackagingRoute
  '/donor/profile': typeof DonorProfileRoute
  '/donor/review': typeof DonorReviewRoute
  '/donor/schedule': typeof DonorScheduleRoute
  '/ngo/dashboard': typeof NgoDashboardRoute
  '/ngo/demands': typeof NgoDemandsRouteWithChildren
  '/ngo/incoming': typeof NgoIncomingRoute
  '/ngo/notifications': typeof NgoNotificationsRoute
  '/ngo/profile': typeof NgoProfileRoute
  '/register/donor': typeof RegisterDonorRoute
  '/register/ngo': typeof RegisterNgoRoute
  '/register/': typeof RegisterIndexRoute
  '/donor/matches/$id': typeof DonorMatchesIdRoute
  '/donor/track/$id': typeof DonorTrackIdRoute
  '/ngo/demands/new': typeof NgoDemandsNewRoute
  '/ngo/demands/': typeof NgoDemandsIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/about'
    | '/admin'
    | '/contact'
    | '/donor'
    | '/faq'
    | '/find-ngos'
    | '/how-it-works'
    | '/login'
    | '/ngo'
    | '/register'
    | '/admin/analytics'
    | '/admin/dashboard'
    | '/admin/ngos'
    | '/admin/system-health'
    | '/donor/camera'
    | '/donor/dashboard'
    | '/donor/detections'
    | '/donor/donate'
    | '/donor/donations'
    | '/donor/impact'
    | '/donor/matches'
    | '/donor/notifications'
    | '/donor/packaging'
    | '/donor/profile'
    | '/donor/review'
    | '/donor/schedule'
    | '/ngo/dashboard'
    | '/ngo/demands'
    | '/ngo/incoming'
    | '/ngo/notifications'
    | '/ngo/profile'
    | '/register/donor'
    | '/register/ngo'
    | '/register/'
    | '/donor/matches/$id'
    | '/donor/track/$id'
    | '/ngo/demands/new'
    | '/ngo/demands/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/about'
    | '/admin'
    | '/contact'
    | '/donor'
    | '/faq'
    | '/find-ngos'
    | '/how-it-works'
    | '/login'
    | '/ngo'
    | '/admin/analytics'
    | '/admin/dashboard'
    | '/admin/ngos'
    | '/admin/system-health'
    | '/donor/camera'
    | '/donor/dashboard'
    | '/donor/detections'
    | '/donor/donate'
    | '/donor/donations'
    | '/donor/impact'
    | '/donor/matches'
    | '/donor/notifications'
    | '/donor/packaging'
    | '/donor/profile'
    | '/donor/review'
    | '/donor/schedule'
    | '/ngo/dashboard'
    | '/ngo/incoming'
    | '/ngo/notifications'
    | '/ngo/profile'
    | '/register/donor'
    | '/register/ngo'
    | '/register'
    | '/donor/matches/$id'
    | '/donor/track/$id'
    | '/ngo/demands/new'
    | '/ngo/demands'
  id:
    | '__root__'
    | '/'
    | '/about'
    | '/admin'
    | '/contact'
    | '/donor'
    | '/faq'
    | '/find-ngos'
    | '/how-it-works'
    | '/login'
    | '/ngo'
    | '/register'
    | '/admin/analytics'
    | '/admin/dashboard'
    | '/admin/ngos'
    | '/admin/system-health'
    | '/donor/camera'
    | '/donor/dashboard'
    | '/donor/detections'
    | '/donor/donate'
    | '/donor/donations'
    | '/donor/impact'
    | '/donor/matches'
    | '/donor/notifications'
    | '/donor/packaging'
    | '/donor/profile'
    | '/donor/review'
    | '/donor/schedule'
    | '/ngo/dashboard'
    | '/ngo/demands'
    | '/ngo/incoming'
    | '/ngo/notifications'
    | '/ngo/profile'
    | '/register/donor'
    | '/register/ngo'
    | '/register/'
    | '/donor/matches/$id'
    | '/donor/track/$id'
    | '/ngo/demands/new'
    | '/ngo/demands/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AboutRoute: typeof AboutRoute
  AdminRoute: typeof AdminRouteWithChildren
  ContactRoute: typeof ContactRoute
  DonorRoute: typeof DonorRouteWithChildren
  FaqRoute: typeof FaqRoute
  FindNgosRoute: typeof FindNgosRoute
  HowItWorksRoute: typeof HowItWorksRoute
  LoginRoute: typeof LoginRoute
  NgoRoute: typeof NgoRouteWithChildren
  RegisterRoute: typeof RegisterRouteWithChildren
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/register': {
      id: '/register'
      path: '/register'
      fullPath: '/register'
      preLoaderRoute: typeof RegisterRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/ngo': {
      id: '/ngo'
      path: '/ngo'
      fullPath: '/ngo'
      preLoaderRoute: typeof NgoRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/how-it-works': {
      id: '/how-it-works'
      path: '/how-it-works'
      fullPath: '/how-it-works'
      preLoaderRoute: typeof HowItWorksRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/find-ngos': {
      id: '/find-ngos'
      path: '/find-ngos'
      fullPath: '/find-ngos'
      preLoaderRoute: typeof FindNgosRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/faq': {
      id: '/faq'
      path: '/faq'
      fullPath: '/faq'
      preLoaderRoute: typeof FaqRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/donor': {
      id: '/donor'
      path: '/donor'
      fullPath: '/donor'
      preLoaderRoute: typeof DonorRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/contact': {
      id: '/contact'
      path: '/contact'
      fullPath: '/contact'
      preLoaderRoute: typeof ContactRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin': {
      id: '/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AdminRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/about': {
      id: '/about'
      path: '/about'
      fullPath: '/about'
      preLoaderRoute: typeof AboutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/register/': {
      id: '/register/'
      path: '/'
      fullPath: '/register/'
      preLoaderRoute: typeof RegisterIndexRouteImport
      parentRoute: typeof RegisterRoute
    }
    '/register/ngo': {
      id: '/register/ngo'
      path: '/ngo'
      fullPath: '/register/ngo'
      preLoaderRoute: typeof RegisterNgoRouteImport
      parentRoute: typeof RegisterRoute
    }
    '/register/donor': {
      id: '/register/donor'
      path: '/donor'
      fullPath: '/register/donor'
      preLoaderRoute: typeof RegisterDonorRouteImport
      parentRoute: typeof RegisterRoute
    }
    '/ngo/profile': {
      id: '/ngo/profile'
      path: '/profile'
      fullPath: '/ngo/profile'
      preLoaderRoute: typeof NgoProfileRouteImport
      parentRoute: typeof NgoRoute
    }
    '/ngo/notifications': {
      id: '/ngo/notifications'
      path: '/notifications'
      fullPath: '/ngo/notifications'
      preLoaderRoute: typeof NgoNotificationsRouteImport
      parentRoute: typeof NgoRoute
    }
    '/ngo/incoming': {
      id: '/ngo/incoming'
      path: '/incoming'
      fullPath: '/ngo/incoming'
      preLoaderRoute: typeof NgoIncomingRouteImport
      parentRoute: typeof NgoRoute
    }
    '/ngo/demands': {
      id: '/ngo/demands'
      path: '/demands'
      fullPath: '/ngo/demands'
      preLoaderRoute: typeof NgoDemandsRouteImport
      parentRoute: typeof NgoRoute
    }
    '/ngo/dashboard': {
      id: '/ngo/dashboard'
      path: '/dashboard'
      fullPath: '/ngo/dashboard'
      preLoaderRoute: typeof NgoDashboardRouteImport
      parentRoute: typeof NgoRoute
    }
    '/donor/schedule': {
      id: '/donor/schedule'
      path: '/schedule'
      fullPath: '/donor/schedule'
      preLoaderRoute: typeof DonorScheduleRouteImport
      parentRoute: typeof DonorRoute
    }
    '/donor/review': {
      id: '/donor/review'
      path: '/review'
      fullPath: '/donor/review'
      preLoaderRoute: typeof DonorReviewRouteImport
      parentRoute: typeof DonorRoute
    }
    '/donor/profile': {
      id: '/donor/profile'
      path: '/profile'
      fullPath: '/donor/profile'
      preLoaderRoute: typeof DonorProfileRouteImport
      parentRoute: typeof DonorRoute
    }
    '/donor/packaging': {
      id: '/donor/packaging'
      path: '/packaging'
      fullPath: '/donor/packaging'
      preLoaderRoute: typeof DonorPackagingRouteImport
      parentRoute: typeof DonorRoute
    }
    '/donor/notifications': {
      id: '/donor/notifications'
      path: '/notifications'
      fullPath: '/donor/notifications'
      preLoaderRoute: typeof DonorNotificationsRouteImport
      parentRoute: typeof DonorRoute
    }
    '/donor/matches': {
      id: '/donor/matches'
      path: '/matches'
      fullPath: '/donor/matches'
      preLoaderRoute: typeof DonorMatchesRouteImport
      parentRoute: typeof DonorRoute
    }
    '/donor/impact': {
      id: '/donor/impact'
      path: '/impact'
      fullPath: '/donor/impact'
      preLoaderRoute: typeof DonorImpactRouteImport
      parentRoute: typeof DonorRoute
    }
    '/donor/donations': {
      id: '/donor/donations'
      path: '/donations'
      fullPath: '/donor/donations'
      preLoaderRoute: typeof DonorDonationsRouteImport
      parentRoute: typeof DonorRoute
    }
    '/donor/donate': {
      id: '/donor/donate'
      path: '/donate'
      fullPath: '/donor/donate'
      preLoaderRoute: typeof DonorDonateRouteImport
      parentRoute: typeof DonorRoute
    }
    '/donor/detections': {
      id: '/donor/detections'
      path: '/detections'
      fullPath: '/donor/detections'
      preLoaderRoute: typeof DonorDetectionsRouteImport
      parentRoute: typeof DonorRoute
    }
    '/donor/dashboard': {
      id: '/donor/dashboard'
      path: '/dashboard'
      fullPath: '/donor/dashboard'
      preLoaderRoute: typeof DonorDashboardRouteImport
      parentRoute: typeof DonorRoute
    }
    '/donor/camera': {
      id: '/donor/camera'
      path: '/camera'
      fullPath: '/donor/camera'
      preLoaderRoute: typeof DonorCameraRouteImport
      parentRoute: typeof DonorRoute
    }
    '/admin/system-health': {
      id: '/admin/system-health'
      path: '/system-health'
      fullPath: '/admin/system-health'
      preLoaderRoute: typeof AdminSystemHealthRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/ngos': {
      id: '/admin/ngos'
      path: '/ngos'
      fullPath: '/admin/ngos'
      preLoaderRoute: typeof AdminNgosRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/dashboard': {
      id: '/admin/dashboard'
      path: '/dashboard'
      fullPath: '/admin/dashboard'
      preLoaderRoute: typeof AdminDashboardRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/analytics': {
      id: '/admin/analytics'
      path: '/analytics'
      fullPath: '/admin/analytics'
      preLoaderRoute: typeof AdminAnalyticsRouteImport
      parentRoute: typeof AdminRoute
    }
    '/ngo/demands/': {
      id: '/ngo/demands/'
      path: '/'
      fullPath: '/ngo/demands/'
      preLoaderRoute: typeof NgoDemandsIndexRouteImport
      parentRoute: typeof NgoDemandsRoute
    }
    '/ngo/demands/new': {
      id: '/ngo/demands/new'
      path: '/new'
      fullPath: '/ngo/demands/new'
      preLoaderRoute: typeof NgoDemandsNewRouteImport
      parentRoute: typeof NgoDemandsRoute
    }
    '/donor/track/$id': {
      id: '/donor/track/$id'
      path: '/track/$id'
      fullPath: '/donor/track/$id'
      preLoaderRoute: typeof DonorTrackIdRouteImport
      parentRoute: typeof DonorRoute
    }
    '/donor/matches/$id': {
      id: '/donor/matches/$id'
      path: '/$id'
      fullPath: '/donor/matches/$id'
      preLoaderRoute: typeof DonorMatchesIdRouteImport
      parentRoute: typeof DonorMatchesRoute
    }
  }
}

interface AdminRouteChildren {
  AdminAnalyticsRoute: typeof AdminAnalyticsRoute
  AdminDashboardRoute: typeof AdminDashboardRoute
  AdminNgosRoute: typeof AdminNgosRoute
  AdminSystemHealthRoute: typeof AdminSystemHealthRoute
}

const AdminRouteChildren: AdminRouteChildren = {
  AdminAnalyticsRoute: AdminAnalyticsRoute,
  AdminDashboardRoute: AdminDashboardRoute,
  AdminNgosRoute: AdminNgosRoute,
  AdminSystemHealthRoute: AdminSystemHealthRoute,
}

const AdminRouteWithChildren = AdminRoute._addFileChildren(AdminRouteChildren)

interface DonorMatchesRouteChildren {
  DonorMatchesIdRoute: typeof DonorMatchesIdRoute
}

const DonorMatchesRouteChildren: DonorMatchesRouteChildren = {
  DonorMatchesIdRoute: DonorMatchesIdRoute,
}

const DonorMatchesRouteWithChildren = DonorMatchesRoute._addFileChildren(
  DonorMatchesRouteChildren,
)

interface DonorRouteChildren {
  DonorCameraRoute: typeof DonorCameraRoute
  DonorDashboardRoute: typeof DonorDashboardRoute
  DonorDetectionsRoute: typeof DonorDetectionsRoute
  DonorDonateRoute: typeof DonorDonateRoute
  DonorDonationsRoute: typeof DonorDonationsRoute
  DonorImpactRoute: typeof DonorImpactRoute
  DonorMatchesRoute: typeof DonorMatchesRouteWithChildren
  DonorNotificationsRoute: typeof DonorNotificationsRoute
  DonorPackagingRoute: typeof DonorPackagingRoute
  DonorProfileRoute: typeof DonorProfileRoute
  DonorReviewRoute: typeof DonorReviewRoute
  DonorScheduleRoute: typeof DonorScheduleRoute
  DonorTrackIdRoute: typeof DonorTrackIdRoute
}

const DonorRouteChildren: DonorRouteChildren = {
  DonorCameraRoute: DonorCameraRoute,
  DonorDashboardRoute: DonorDashboardRoute,
  DonorDetectionsRoute: DonorDetectionsRoute,
  DonorDonateRoute: DonorDonateRoute,
  DonorDonationsRoute: DonorDonationsRoute,
  DonorImpactRoute: DonorImpactRoute,
  DonorMatchesRoute: DonorMatchesRouteWithChildren,
  DonorNotificationsRoute: DonorNotificationsRoute,
  DonorPackagingRoute: DonorPackagingRoute,
  DonorProfileRoute: DonorProfileRoute,
  DonorReviewRoute: DonorReviewRoute,
  DonorScheduleRoute: DonorScheduleRoute,
  DonorTrackIdRoute: DonorTrackIdRoute,
}

const DonorRouteWithChildren = DonorRoute._addFileChildren(DonorRouteChildren)

interface NgoDemandsRouteChildren {
  NgoDemandsNewRoute: typeof NgoDemandsNewRoute
  NgoDemandsIndexRoute: typeof NgoDemandsIndexRoute
}

const NgoDemandsRouteChildren: NgoDemandsRouteChildren = {
  NgoDemandsNewRoute: NgoDemandsNewRoute,
  NgoDemandsIndexRoute: NgoDemandsIndexRoute,
}

const NgoDemandsRouteWithChildren = NgoDemandsRoute._addFileChildren(
  NgoDemandsRouteChildren,
)

interface NgoRouteChildren {
  NgoDashboardRoute: typeof NgoDashboardRoute
  NgoDemandsRoute: typeof NgoDemandsRouteWithChildren
  NgoIncomingRoute: typeof NgoIncomingRoute
  NgoNotificationsRoute: typeof NgoNotificationsRoute
  NgoProfileRoute: typeof NgoProfileRoute
}

const NgoRouteChildren: NgoRouteChildren = {
  NgoDashboardRoute: NgoDashboardRoute,
  NgoDemandsRoute: NgoDemandsRouteWithChildren,
  NgoIncomingRoute: NgoIncomingRoute,
  NgoNotificationsRoute: NgoNotificationsRoute,
  NgoProfileRoute: NgoProfileRoute,
}

const NgoRouteWithChildren = NgoRoute._addFileChildren(NgoRouteChildren)

interface RegisterRouteChildren {
  RegisterDonorRoute: typeof RegisterDonorRoute
  RegisterNgoRoute: typeof RegisterNgoRoute
  RegisterIndexRoute: typeof RegisterIndexRoute
}

const RegisterRouteChildren: RegisterRouteChildren = {
  RegisterDonorRoute: RegisterDonorRoute,
  RegisterNgoRoute: RegisterNgoRoute,
  RegisterIndexRoute: RegisterIndexRoute,
}

const RegisterRouteWithChildren = RegisterRoute._addFileChildren(
  RegisterRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AboutRoute: AboutRoute,
  AdminRoute: AdminRouteWithChildren,
  ContactRoute: ContactRoute,
  DonorRoute: DonorRouteWithChildren,
  FaqRoute: FaqRoute,
  FindNgosRoute: FindNgosRoute,
  HowItWorksRoute: HowItWorksRoute,
  LoginRoute: LoginRoute,
  NgoRoute: NgoRouteWithChildren,
  RegisterRoute: RegisterRouteWithChildren,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
